### ISSUE TITLE
SSL certificate error with python3.9

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api-client#13]
## 🐛 Describe the bug
When requesting pds-gamma with python 3.9 there is an SSL certificate error

it works with python 3.7

See: 
```
Traceback (most recent call last):
  File "/Users/loubrieu/tmp/test.py", line 6, in <module>
    bundles.bundle_by_lidvid('urn:nasa:pds:insight_documents::2.0')
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/api/bundles_api.py", line 67, in bundle_by_lidvid
    return self.bundle_by_lidvid_with_http_info(lidvid, **kwargs)  # noqa: E501
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/api/bundles_api.py", line 158, in bundle_by_lidvid_with_http_info
    return self.api_client.call_api(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/api_client.py", line 376, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/api_client.py", line 186, in __call_api
    response_data = self.request(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/api_client.py", line 402, in request
    return self.rest_client.GET(url,
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/rest.py", line 238, in GET
    return self.request("GET", url,
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/pds/api_client/rest.py", line 204, in request
    r = self.pool_manager.request(method, url,
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/loubrieu/tmp/venv-api39/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pds-gamma.jpl.nasa.gov', port=443): Max retries exceeded with url: /api/bundles/urn%3Anasa%3Apds%3Ainsight_documents%3A%3A2.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

```

## 📜 To Reproduce
1. python -m venv venv # using python 3.9
2. source venv
3. pip install pds.api-client
4. python test.py

[test.py.zip](https://github.com/NASA-PDS/pds-api-client/files/7324095/test.py.zip)

## 🕵️ Expected behavior

The code should return the requested bundle

## 📚 Version of Software Used

0.7.1

## 🖥 System Info

---

**Comment by nutjob4life** [comment]
@tloubrieu-jpl For a short-term workaround for @gxtchen, you could put this at the top of `test.py`:
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
This will turn off all certificate validation until such time that the Python 3.9 installation can be fixed.

**Comment by tloubrieu-jpl** [comment]
@gxtchen , you need to run `pip install --upgrade certifi` in your virtual environment. Let me know if that helps.
